trusted-substituters = https://cache.nixos.org https://dconf2nix.cachix.org https://cache.garnix.io
trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
auto-optimise-store = true
keep-outputs = true
keep-derivations = true
warn-dirty = false
download-buffer-size = 524288000